id: 6dca2137df634129a30956c833da52b4
initial_creation_type: ebook
created_at: 12/10/2021
last_modified_at: 26/11/2021
source_metadata:
  title: test
  subtitle: test
  authors:
  - test
  collection: test
  publisher: test
  id: test
  cover: tmp11rccwle.jpg
  credit: tmptbttxfq9.jpg
